#!/usr/bin/env bash
# scripts/check-user-facing-copy.sh
#
# Pre-commit / pre-deploy check: catch dev markers, vendor watermarks,
# and AI self-references in user-facing copy before they ship to production.
#
# Usage:
#   ./scripts/check-user-facing-copy.sh
#
# Exits 0 if clean, 1 if issues found.
#
# Scope:
#   - src/        (all .tsx/.ts)
#   - content/    (all .mdx)
#   - public/     (skipped — image assets)
#
# Excluded:
#   - src/app/api/        (server-side only, never reaches browser)
#   - src/lib/            (server-side helpers)
#   - node_modules/
#   - .next/

set -e

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

# Colors
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'

ISSUES=0

scan() {
  local label="$1"
  local pattern="$2"
  local severity="$3" # "error" or "warn"

  # Search user-facing dirs only
  # - src/app/[not api] = page files
  # - src/components/ = React components
  # - content/ = MDX articles
  local hits
  hits=$(grep -rnE "$pattern" \
    src/app/ \
    src/components/ \
    content/ \
    --include="*.tsx" --include="*.ts" --include="*.mdx" 2>/dev/null \
    | grep -v node_modules || true)

  if [ -n "$hits" ]; then
    if [ "$severity" = "error" ]; then
      echo -e "${RED}❌ [ERROR] $label${NC}"
      echo "$hits" | sed 's/^/   /'
      echo ""
      ISSUES=$((ISSUES + 1))
    else
      echo -e "${YELLOW}⚠️  [WARN]  $label${NC}"
      echo "$hits" | sed 's/^/   /'
      echo ""
    fi
  fi
}

echo "🔍 Scanning user-facing copy for dev markers / vendor watermarks..."
echo ""

# === Errors (block deploy) ===

scan "Vendor watermark 'Powered by' / 'Built with' / 'Hosted on'" \
  "(Powered by|Built with|Hosted on|Deployed via|runs on|stacks?:)" \
  "error"

scan "Dev status markers (Coming soon / TBD / TODO / FIXME / MVP / beta)" \
  "(Coming soon|TBD|TODO|FIXME|\\bMVP\\b|\\bbeta\\b|placeholder text|sample text|sample data)" \
  "error"

scan "AI self-references in user-facing copy" \
  "(As an AI assistant|I'm an AI|Generated by AI|Language model|GPT-[0-9]|ChatGPT|Claude)" \
  "error"

scan "Lorem ipsum / fake data leaks" \
  "(Lorem ipsum|test@test\\.com|placeholder@example)" \
  "error"

# === Warnings (review but don't block) ===

scan "Internal status words (review manually)" \
  "(WIP|in progress|not yet implemented)" \
  "warn"

# === Final report ===

if [ "$ISSUES" -gt 0 ]; then
  echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${RED}  Found $ISSUES blocker(s). Fix before deploying.${NC}"
  echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  exit 1
fi

echo -e "${GREEN}✅ All user-facing copy checks passed.${NC}"
echo ""
echo "What we checked:"
echo "  • No vendor watermarks (Powered by X / Built with X / Hosted on X)"
echo "  • No dev markers (Coming soon / TBD / TODO / MVP)"
echo "  • No AI self-references in user copy"
echo "  • No Lorem ipsum / fake test data"
echo ""
echo "Tip: add this to .husky/pre-commit or GitHub Action to enforce."
exit 0